# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Lexi's Blog
email: lex@lex.me.uk
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lex.me.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lexil
github_username: lexicality
steam_username: lexicality

permalink: /blog/:categories/:slug

excerpt_separator: "<!-- more -->"

pagination:
  enabled: true
  per_page: 2 #10
  permalink: /:num/
  sort_reverse: true

autopages:
  enabled: true

  categories:
    layouts:
      - archive_cats.html
    title: "Archive for :nicename"
    permalink: "/blog/:cat"

  tags:
    layouts:
      - archive_tags.html
    title: "Archive for tag :nicename"
    permalink: "/blog/tags/:tag"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: csharp
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-paginate-v2
  - jekyll-sitemap
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
